### DISCUSSION TITLE
Help of configuring spring cloud parameterstore (spring boot 3)

### DISCUSSION THREAD

**Discussion by ismurygin** [awspring/spring-cloud-aws#1181] [Q&A]
Hello folks!
Is it possible to use `spring-cloud-aws-starter-parameter-store`, to retrieve secrets from AWS parameter store for the local developement?
So I have the next dependencies now
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.1</version>
		<relativePath />
	</parent>

...

		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-aws-starter-parameter-store</artifactId>
		</dependency>
```

The dependecy tree is following
```
[INFO] +- io.awspring.cloud:spring-cloud-aws-starter-parameter-store:jar:3.1.1:compile
[INFO] |  \- io.awspring.cloud:spring-cloud-aws-parameter-store:jar:3.1.1:compile
[INFO] |     \- software.amazon.awssdk:ssm:jar:2.21.46:compile
```
And I would like to make the configuration like
application-local.yml
```
spring:
  config:
    import: <DO I NEED TO PROVIDE full AWS ARN ADDRESS here?>/config/${spring.application.name}_${spring.profiles.active}/
  cloud:
    aws:
      region:
        static: us-west-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      parameterstore:
        enabled: true
```
 
If I just write like 
```
  config:
    import: aws-parameterstore:/config/${spring.application.name}_${spring.profiles.active}/
```

then I get 
```
software.amazon.awssdk.services.ssm.model.SsmException: The security token included in the request is invalid. (Service: Ssm, Status Code: 400, Request ID: blabla)
```
