### DISCUSSION TITLE
Multiple database configuration using Spring Boot configuration files

### DISCUSSION THREAD

**Discussion by vmatos** [awspring/spring-cloud-aws#125] [Q&A]
Hello,

I would like to understand if I am able/should be able to use Spring Boot configuration files to configure multiple datasources.
e.g. multiple databases in a single RDS instance.

Partial `application.yaml` of what I have tried:
```
cloud:
  aws:
    rds:
      instances0:
        dbInstanceIdentifier: instance1
        username: identifier1
        password: identifier1
        databaseName: databaseA_in_instance1
      instances1:
        dbInstanceIdentifier: instance1
        username: identifier1
        password: identifier1
        databaseName: databaseB_in_instance1
```

However, I get an Exception of duplicated bean `instance1`.

If I am not able to do it in the configuration files, how could I achieve it?

**Comment by mkatircioglu** [comment]
Multiple Datasources are supposed to be defined as list in application.yaml. Could you please try following instead? @vmatos 

```
cloud:
  aws:
    rds:
      - dbInstanceIdentifier: instance1
        username: identifier1
        password: identifier1
        databaseName: databaseA_in_instance1
      - dbInstanceIdentifier: instance2
        username: identifier2
        password: identifier2
        databaseName: databaseB_in_instance2
```

**Reply by vmatos** [reply]
I have, and it works for distinct instances.

The use case I am trying, is to connect to multiple databases in a single instance.
Taking your configuration as example:

```
cloud:
  aws:
    rds:
      - dbInstanceIdentifier: instance1
        username: identifier1
        password: identifier1
        databaseName: databaseA_in_instance1
      - dbInstanceIdentifier: instance1
        username: identifier2
        password: identifier2
        databaseName: databaseB_in_instance1
```

I have the feeling my expectation on the usage is wrong, I am just not sure how to achieve.
