### DISCUSSION TITLE
AWS Parameter Store and AWS Secrets Manager left unbound

### DISCUSSION THREAD

**Discussion by github-vemma** [awspring/spring-cloud-aws#247] [Q&A] [answered]
We are using AWS Parameter Store and AWS Secrets Manager in our application and they have worked fine. We are upgrading our application from Spring Boot 2.2.7 and Spring Cloud Greenwich to Spring Boot 2.6.3, Spring Cloud 2021.0.0 and Spring Cloud AWS 2.3.3. 

Now application gives error concerning aws-parameterstore and aws-secretsmanager

Binding to target [Bindable@2a3888c1 type = java.util.List<org.springframework.boot.context.config.ConfigDataLocation>, value = 'none', annotations = array<Annotation>[@org.springframework.boot.context.properties.bind.Name(value=\"import\")]] failed:    
Property: spring.config.import[0].aws-parameterstore    Value: /config/application/    
Origin: class path resource [application-aws.yml] from app.jar - 4:29    
Reason: The elements [spring.config.import[0].aws-parameterstore,spring.config.import[1].aws-secretmanager] were left unbound.    
Property: spring.config.import[1].aws-secretmanager    Value: /secret/application/    
Origin: class path resource [application-aws.yml] from app.jar - 5:28    
Reason: The elements [spring.config.import[0].aws-parameterstore,spring.config.import[1].aws-secretmanager] were left unbound.
Action: Update your application's configuration

In our application-aws.yml file we have

spring:
  config:
    import:
      - aws-parameterstore:
      - aws-secretsmanager:
     
aws:
  paramstore:
    default-context: application
    enabled: true
    failFast: false
    prefix: /config
    region: eu-central-1
  secretsmanager:
    default-context: application
    enabled: true
    fail-fast: false
    prefix: /secret
    region: eu-central-1

We don't have spring.application.name in our application.yml files.

On AWS we have a lot of parameters e.g. 

/config/application/dynatrace.url
/config/application/dynatrace.token
/config/application/postgres.host
/config/application/postgres.port

and secrets under /secret/application e.g.

postgres.password
postgres.username

I have thought that all parameters and secrets are loaded like earlier. Earlier we used also bootstrap.yml. 

What have I done wrong or what I have not noticed?

**Comment by maciejwalkowiak** [comment, marked as answer]
@github-vemma can you try with Spring Cloud AWS 2.4.0 (as its compatible with Spring Boot 2.6). If same problem happens we will investigate.

**Reply by github-vemma** [reply]
I tested with

- Spring Cloud AWS 2.4.0
- Spring Cloud 2021.0.0
- Spring Boot 2.6.3

First I added missing optionals and I used this kind configuration in application.yml file

```
spring:
  config:
    import:
      - optional:aws-parameterstore:
      - optional:aws-secretsmanager:

aws:
  paramstore:
    default-context: application
    enabled: true
    failFast: false
    prefix: /config
    region: eu-central-1
  secretsmanager:
    default-context: application
    enabled: true
    fail-fast: false
    prefix: /secret
    region: eu-central-1
```
The application failed immediately
```
***************************APPLICATION FAILED TO START***************************
Description:
Binding to target [
	Bindable@4fbe37eb 
		type = java.util.List<org.springframework.boot.context.config.ConfigDataLocation>, 
		value = 'none', 
		annotations = array<Annotation>[@org.springframework.boot.context.properties.bind.Name(value=\"import\")]
	] failed:    
Property: spring.config.import[0].optionalaws-parameterstore    
	Value:     
	Origin: class path resource [application-aws.yml] from app.jar - 4:37    
	Reason: The elements [spring.config.import[0].optionalaws-parameterstore,spring.config.import[1].optionalaws-secretsmanager] were left unbound.    
Property: spring.config.import[1].optionalaws-secretsmanager    
	Value:     
	Origin: class path resource [application-aws.yml] from app.jar - 5:37    
	Reason: The elements [spring.config.import[0].optionalaws-parameterstore,spring.config.import[1].optionalaws-secretsmanager] were left unbound.
Action:Update your application's configuration"
```
		
After that I added single quotation marks as this way
```
spring:
  config:
    import:
      - 'optional:aws-parameterstore:'
      - 'optional:aws-secretsmanager:'
```
Then application started and I found also from the log that properties and secrets were loaded from AWS Parameter Store and Secrets Manager e.g.

io.awspring.cloud.paramstore.AwsParamStorePropertySource Populating property retrieved from AWS Parameter Store: postgres.host

So I had to add quotation marks to spring.config.import.
