### DISCUSSION TITLE
How to configure AWS paramstore with SpringBoot 3.1?

### DISCUSSION THREAD

**Discussion by shawnwoo** [awspring/spring-cloud-aws#837] [Q&A] [answered]
Hi, all: 

Need some help here for how to use the spring cloud aws 3+ with Springboot 3.1. 
Our AWS environment is using the IAM assume roles to get the param store configurations and replacing the value in applicaiton.yml. 
I was using `io.awspring.cloud:spring-cloud-starter-aws-parameter-store-config` with `bootstrap.xml` and it works fine. The aws configurations was get directly from EC2 instance metadata and I don't need put any aws credentials to application.yml. 

After upgrade my service to SpringBoot 3.1, I want to upgrade the param store config to 3 as well. 
Here is the dependencies
```
        implementation "io.awspring.cloud:spring-cloud-aws-starter"
        implementation "io.awspring.cloud:spring-cloud-aws-starter-parameter-store"
``` 
application.yml
```
spring:
  application:
    name: "xxxxx"
  config:
    import: "optional:aws-parameterstore:"
  cloud:
    aws:
      region:
        static: xxxx
```

**Issue**
The application stop to load the configuration from the paramstore to replace the values in application.yml. 
The debug log is showing following: 
```
 DEBUG 8 --- [           main] ParameterStoreConfigDataLocationResolver : Bean of type AwsClientConfigurerParameterStore is not registered: io.awspring.cloud.autoconfigure.config.parameterstore.AwsParameterStoreClientCustomizer has not been registered
```

Any suggestions?
