### ISSUE TITLE
Add 'enabled' Property for Secret Manager configuration

### ISSUE THREAD

**Issue by ielkhalloufi** [awspring/spring-cloud-aws#1005]
**Type**: Feature

I would like to propose the addition of an enabled property for the AWS Secret Manager configuration in Spring Cloud AWS. Currently, there seems to be no direct way to enable or disable the Secret Manager integration globally via configuration properties.

**Describe the solution you'd like**
The enabled property would allow users to programmatically enable or disable the Secret Manager usage in their Spring Cloud applications. This is particularly useful for scenarios where different environments require different configurations or for testing purposes.

**Proposed Solution**
Introduce an enabled property under the spring.cloud.aws.secretsmanager namespace. The property should be a boolean with a default value of true, maintaining the current behavior as the default.

```yml
spring:
  cloud:
    aws:
      secretsmanager:
        enabled: true  # or false to disable the integration
```

Other services already support it, like S3, SES, SNS, SQS and DynamoDB.

**Workaround?**

The SecretManagerConfigDataLocationResolver is part of the internals of the Spring Framework and its lifecycle differs from the regular Spring beans. It is not a bean managed by Spring's application context. It is a component being used during the early stage of application context initialization. Therefore, it doesn't fall under Spring's bean management system and cannot be mocked using @MockBean annotation like other auto-configured beans.

The only workaround I can think of is the following:

Do not specify the spring cloud config in your `application.yml`:
```yml
spring:
#  cloud:
#    aws:
#     parameterstore:

```

But, add the configuration in a separate environment application yaml file, like for example, `application-prd.yml`:
```yml
spring:
  config:
    import: aws-secretsmanager:/ms/common?prefix=common;
  cloud:
    aws:
      secretsmanager:
        reload:
          period: 60s
          strategy: refresh

```

By doing so, your specific test config yaml, like for example:`application-integration-test.yml`, will not inherit the config, and is because of that disabled.

The downside is that, you need to duplicate the spring cloud config to all environments (application-acc.yml etc.).

Btw, also, overriding the `config.activate.on-profile` does not work.
