### ISSUE TITLE
S3 endpoint is not overridden via properties file

### ISSUE THREAD

**Issue by siegolas2** [awspring/spring-cloud-aws#1119]
**Type**: Bug

**Component**: S3

**Describe the bug**
Using `io.awspring.cloud` version 3.1.0
Using dependencies: `spring-cloud-aws-starter` and `spring-cloud-aws-starter-s3`. Also using `spring-cloud-aws-starter-sns` and `spring-cloud-aws-starter-sqs`

S3 endpoint is not overridden although I'm applying the expected property in the properties files. But for SQS is working so I guess this component lack the proper code regarding auto configuration.

Among others, I apply these configs:
```
spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: eu-west-1
      credentials:
        instance-profile: false
        access-key: testAccessKey
        secret-key: testSecretKey
      s3:
        endpoint: http://localhost:4566 
```

And still I can only achieve the endpoint url being overridden applying the code:
```
S3Client s3Client() {
    S3Client s3Client =  S3Client.builder()
            .endpointOverride(URI.create(LOCALSTACK_URL))
            .region(Region.of(amazonS3Properties.region))
            .forcePathStyle(true)
            .build()
```
Can you check whether the endpoint assignment is not covered in the auto configuration step for S3?

Without applying `.endpointOverride(URI.create(LOCALSTACK_URL))` assignment, declaring a bean like:
```
@Bean
fun s3Client(): S3Client = S3Client.builder().region(Region.of(amazonS3Properties.region)).build()
```
returns a S3Client pointing to `https://s3.eu-west-1.amazonaws.com` instead of `http://localhost:4566`

**Sample**
I provide a screenshot to show the result, showing the value of the "java.net.URI" property

<img width="1070" alt="Screenshot 2024-03-26 at 14 47 30" src="https://github.com/awspring/spring-cloud-aws/assets/161936503/08094a11-6cc1-4918-89a9-c057d74cb550">
