### ISSUE TITLE
Enhance RegionProviderAutoConfiguration make profile configuration easier

### ISSUE THREAD

**Issue by wmz7year** [awspring/spring-cloud-aws#1125]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
Currently when a project wants to use profile configuration with credentials and regions, we need to configure twice profile configuration.
for example:
```
spring:
  cloud:
    aws:
      credentials:
        profile:
          name: example
      region:
        profile:
          name: example
```

Even if profile's credential region as same as region.

**Describe the solution you'd like**

If we can enhance `RegionProviderAutoConfiguration` load credential configuration when the region profile doesn't exist, it will be easier to use profile configuration.

example:

```
spring:
  cloud:
    aws:
      credentials:
        profile:
          name: example
```

**Describe alternatives you've considered**
Because AWS credential profile already contains region configuration, it will be more clear and easier to use this configure method.

**Additional context**
