### ISSUE TITLE
S3 KMS condition has incorrect capitalization

### ISSUE THREAD

**Issue by gbaso** [awspring/spring-cloud-aws#1333]
**Type**: Bug

**Component**:
S3

**Describe the bug**
`S3EncryptionConditional` has a nested condition `KmsKeyProperty` which is conditional on property `spring.cloud.aws.s3.encryption.keyId`. According to property binding rules, `keyId` should be `key-id`. This is also reflected in the following section of the autogenerated `spring-configuration-metadata.json`:

```json
{
  "name": "spring.cloud.aws.s3.encryption.key-id",
  "type": "java.lang.String",
  "sourceType": "io.awspring.cloud.autoconfigure.s3.properties.S3EncryptionProperties"
}
```

which is the property name suggested by the IDE. Unfortunately this causes the condition not to match, leading to the creation of an S3Client *without* client-side encryption enabled. To match the condition, `keyId` must be used in the application.yaml instead of `key-id`.

**Sample**

```yaml
spring:
  cloud:
    aws:
      credentials:
        ...
      s3:
        encryption:
          key-id: aaaaaaaa-bbbb-4444-cccc-dddddddddddd
```

```java
@Autowired
S3Client s3Client;

assert s3Client instanceof S3EncryptionClient; // fails
```
