### ISSUE TITLE
SQS Global Deletion Policy does not appear to work.

### ISSUE THREAD

**Issue by joelhess-icario** [awspring/spring-cloud-aws#156]
**Type**: Bug

**Component**:
SQS

**Describe the bug**
Using v2.3.0 
spring boot 2.4.1, 
Kotlin 1.4 
Following the documentation from: https://docs.awspring.io/spring-cloud-aws/docs/2.3.0-RC2/reference/html/index.html#deletion-policies

Declaring the SQS deletion policy to be `ON_SUCCESS` globally in my app yaml does not appear to have any impact. We see messages that are successfully handled (no exceptions) being processed multiple time, and completing well within the visibility timeout. Using the value at the annotation seems to work. 

**Sample**
snip from application.yaml 
```
cloud:
  aws:
    region:
      static: "us-east-2"
    credentials:
      instanceProfile: true
    stack:
      auto: false
    sqs:
      handler:
        default-deletion-policy: on_success  // Also tried ON_SUCCESS
```
