### ISSUE TITLE
Unable to load property from AWS secrets manager without creating all the the possible secret names.

### ISSUE THREAD

**Issue by amrutprabhu** [awspring/spring-cloud-aws#189]
**Type**: Bug

**Component**:
Secrets Manager

**Describe the bug**

So I am trying to get a secret from the secrets manager, and I am not able to get the secret unless I create all the possible secret names on AWS secrets-manager.

Pom.xml
```
                  <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
			<version>3.0.4</version>
		</dependency>
		<dependency>
			<groupId>io.awspring.cloud</groupId>
			<artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.awspring.cloud</groupId>
				<artifactId>spring-cloud-aws-dependencies</artifactId>
				<version>2020.0.4</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
```
application.yaml
```
spring:
  application:
    name: config-client
  config:
    import: "aws-secretsmanager:"


secret-manager-property: "local secret manager property"
```
bootstrap.yaml

```
spring:
  application:
    name: config-client
  config:
    import: "aws-secretsmanager:"
aws:
  secretsmanager:
    prefix: /secret
    name: config-client
    defaultContext: application
    enabled: true
    profile-separator: '-'
    region: "eu-central-1"
```
secrets created on AWS :
1. /secret/config-client
2. /secret-config-client-aws
3. /secret/application

all the above three secrets contain a secret key `secret-manager-property`.

When I run the application to load the property `secret-manager-property`, it fails with the following error.
```

Config data resource '[AwsSecretsManagerConfigDataResource@6cd166b8 context = '/secret/application-default', optional = false]' via location 'aws-secretsmanager:' does not exist
```
**Question:** Shouldn't it load the property using the secret  `/secret/config-client` since there is no profile specified (meaning default profile)?

because of the error above, I then create the `/secret/application-default` , just to satisfy it. but now it falls for this error. 

```

Config data resource '[AwsSecretsManagerConfigDataResource@38af1bf6 context = '/secret/config-client-default', optional = false]' via location 'aws-secretsmanager:' does not exist

Action:

Check that the value 'aws-secretsmanager:' at class path resource [bootstrap.yaml] - 23:13 is correct, or prefix it with 'optional:'
```

Because of this error, I create the secret it asked, ie. `/secret/config-client-default`, 

Funny thing is, after creating this secret it then loaded the value from the `/secret/config-client`. :smile: 

**Question:**
So shouldn't it have already loaded the property from the `/secret/config-client` secret without even me creating the other two?
