### ISSUE TITLE
Secrets manager - Not merging list items into @ConfigurationProperties

### ISSUE THREAD

**Issue by Adam1901** [awspring/spring-cloud-aws#220]
**Type**: Bug

**Component**:
"Secrets Manager"

**Describe the bug**
Secrets manager populating a configuration list is not merging hardcoded values and secrets values correctly.

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

```
application.yml
stripe:
  api-key:
  webhook-secret: 
  currencies:
    - currencyType: GBP
      prefix: '£'
      supporter:
        priceId: 
        amount: '4.99'
   - currencyType: USD
     prefix: '$'
      supporter:
        priceId: 
        amount: '7'
```

```
Secrets
stripe.currencies[0].supporter.priceId = 'value_amount'
```

```
Mapped into:
@Configuration
@EnableConfigurationProperties
@ConfigurationProperties(value = "stripe")
@Data
public class PaymentConnectorStripeConfiguration {
.....

```

outcome 
empty object with only the secret manager items populated.

Expected
The full objects with the secret manager values populated alongside the hardcoded values
