### ISSUE TITLE
fail-fast too sensitive

### ISSUE THREAD

**Issue by StochasticTinkr** [awspring/spring-cloud-aws#271]
fail-fast causes failure when *any* of the "automatic contexts" aren't valid secrets.   It should instead fail only if no automatic contexts contain valid secrets. 

Example bootstrap.yml:
```
aws:
  secretsmanager:
    enabled: true
    fail-fast: true
    region: us-west-2
    name: my-app-name
```
### Expected
Find and use secret named "/secret/my-app-name_dev"

### Actual
Fails with exception `com.amazonaws.services.secretsmanager.model.ResourceNotFoundException: Secrets Manager can't find the specified secret. (Service: AWSSecretsManager; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: ...; Proxy: null)`

Since I don't have "/secret/application", "/secret/application_dev", nor "/secret/my-app-name".
