### ISSUE TITLE
Retrieve multiple secrets in that have same keys

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#621]
### Discussed in https://github.com/awspring/spring-cloud-aws/discussions/388
To summarize - the issue is that when multiple secrets containing JSON properties are imported, and same keys exist in both secret JSONs then value from one secret overwrites the other.

For example

- `/secret/first-secret`:

```json
{ "username": "postgres" }
```

- `/secret/second-secret`:
```json
{ "username": "root" }
```

I am thinking how this can be solved. We could add a prefix option:

```yml
spring:
    config:
         import: aws-secretsmanager:/secrets/first-secret?prefix=first,aws-secretsmanager:/secret/second-secret?prefix=second
```

Then they would be imported as:

```
first.username=postgres
second.username=root
```
