### ISSUE TITLE
Bean of type AwsClientConfigurerSecretsManager is not registered

### ISSUE THREAD

**Issue by ipsi-apant** [awspring/spring-cloud-aws#907]
**Type**: Issue

### Component:
- Secrets Manager
- spring-cloud-aws-starter-secrets-manager 3.0.2
- software.amazon.awssdk:secretsmanager 2.20.153
- Java 21
- Gradle 8.4-rc-2
- Springboot 3.1.3
- Webflux
- localstack

### logging

```yaml
logging:
  level:
    root: debug
    org:
      springframework: info
      apache.http: info
      hibernate: info
    jdk: info
    software.amazon.awssdk: info
    io:
      awspring.cloud: debug
```

### Description of issue

I am using config.import for loading secrets from secrets-manager. On a dev machine, intellij is able to fetch secrets from localstack during context load. Which is great! Thanks to your efforts making it easier to integrate with AWS cloud.

1) When deploying the same app on a docker container, I am seeing following message in logs. 

_Is it expected?_

2) The application will be deployed on AWS ECS and it will be using `assume-role` for accessing AWS services. So passing credentials in configs file or env var or docker container is not allowed in current infra. My understanding we could use this approach [StsWebIdentityTokenFileCredentialsProvider](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0-SNAPSHOT/reference/html/index.html#stswebidentitytokenfilecredentialsproviderl)

Set `spring.cloud.aws.credentials.sts.role-arn` value.

_Is is correct?_

### Error
```java
SecretsManagerConfigDataLocationResolver : Bean of type AwsClientConfigurerSecretsManager is not registered: io.awspring.cloud.autoconfigure.config.secretsmanager.AwsSecretsManagerClientCustomizer has not been registered

```

### Sample

In java code retrieving secret using `@Value()` annotation.

_application.yaml_

```yaml
spring:
  cloud:
    aws:
      credentials:
        access-key: localstack  # not working if set inside application-dev.yaml
        secret-key: localstack  # not working if set inside application-dev.yaml
      endpoint: ${AWS_ENDPOINT_OVERRIDE:http://localhost:4566}
  config:
    import:
      aws-secretsmanager:${ENV_SECRETS_MANAGER_NAME:default_name}
```

Let me know any more details required.
